workflows:
  default-workflow:
    name: Default
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: latest
    scripts:
      - flutter packages get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk